package:
  name: idigbio
  version: "0.7.1"

source:
  fn: idigbio-0.7.1.tar.gz
  url: https://pypi.python.org/packages/eb/26/cbb8197c8f26890a026ca01b700f8dedc2d396a868fcb1a33df594a31b7a/idigbio-0.7.1.tar.gz
  md5: f7390fea0fbb2f2ee4c04942d5e56523
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - idigbio = idigbio:main
    #
    # Would create an entry point called idigbio that calls idigbio.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - requests

  run:
    - python
    - requests

test:
  # Python imports
  imports:
    - idigbio

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/idigbio/idigbio-python-client/
  license: MIT License
  summary: 'Python Client for the iDigBio Search API'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
